version: '3.7'

services:

  client:
    container_name: just_client
    build: ./src/client
    ports:
      - '3001:3000

  backend:
    container_name: just_backend
    build: ./src/api
    ports:
      - '8000:8080'
    command: npm run start:prod
