version: '3.7'

services:

  client:
    container_name: just_client
    build: ./src/client
    ports:
      - '3001:3000'
    volumes:
      - /usr/src/app/node_modules
      - ./src/client:/usr/src/app

  backend:
    container_name: just_backend
    build: ./src/api
    ports:
      - '8000:8080'
      - '4000:4000'
    volumes:
      - /usr/src/app/node_modules
      - ./src/api:/usr/src/app
      